### PR TITLE
[#54] Update DB

### PR DESCRIPTION
**Pull request by rashadg1030**
```
ERROR:  there is no unique constraint matching given keys for referenced table "repos"
```
I'm still getting this error after adding the constraint:

```
ALTER TABLE ONLY issues
  ADD CONSTRAINT fk_repos FOREIGN KEY (owner, repo_name) 
  REFERENCES repos (owner, name) ON DELETE CASCADE;
```
Gonna try to fix it, but let me know if there is a good way to do this.

### CODE REVIEW

**Comment by rashadg1030** [comment]
I'm not sure if this is possible, but I think for the repo table we can make the `owner` and `repo` the primary key. Can a primary key refer to two different columns? I'll try this.

**Comment by rashadg1030** [comment]
Yes, it's possible. I propose the above idea. If so, does that mean we don't even need `Id`, or is it good to have that for convenience?

**Comment by chshersh** [comment]
@rashadg1030 You can add UNIQUE constraint for pair as well. See how it's done here:

https://stackoverflow.com/questions/14221775/in-postgresql-force-unique-on-combination-of-two-columns

Let's try not to have `name` and `owner` be the primary key. It's much faster if the primary key will be just integer.

Also, I see that this PR is based on your sync worker. And Circle CI is failing because you don't have config from `master`. Could. you, please base this PR on top of `master` and not sync worker? Sync worker is a huge part and probably should be cut into multiple small pieces. We need to merge schema updates first before starting to work on a sync worker, not vice versa.

**Comment by rashadg1030** [comment]
Got it. Will do that. Thank you for the link.

**Pull request closed without merging**
