### PR TITLE
[#43] Add functions for retrieving and parsing cabal files

### LINKED ISSUE #43: Retrieve category from repository Cabal file
We can use the GitHub API to retrieve the contents of a repo's Cabal file. For example pandoc: https://api.github.com/repos/jgm/pandoc/contents/pandoc.cabal

We can then use 
https://www.haskell.org/cabal/release/cabal-latest/doc/API/Cabal/Distribution-PackageDescription-Parsec.html
to parse the file once we retrieve it.

Anything I'm missing anything or suggestions??

### PR DESCRIPTION
**Pull request by rashadg1030**
Resolves #43

### CODE REVIEW

**Comment by rashadg1030** [comment]
Based off of Reddit responses, I think we should give https://hackage.haskell.org/package/http-conduit-2.3.7.1/docs/Network-HTTP-Simple.html as shot.

**Comment by rashadg1030** [comment]
Just tested real quickly in the repl and it seems to work good.

**Comment by rashadg1030** [comment]
```
getCabalFile :: (MonadIO m, WithError m, WithLog env m) => Issue -> m Text
getCabalFile Issue{..} = do
    response <- httpBS request
    let statusCode = getResponseStatusCode response
    -- Add error handling based on status code 
    return $ decodeUtf8 $ getResponseBody $ response
  where
    request :: Request
    request = 
        fromString . unpack $
        "https://raw.githubusercontent.com/" 
        <> unRepoOwner issueRepoOwner
        <> "/" 
        <> unRepoName issueRepoName
        <> "/master/"
        <> unRepoName issueRepoName
        <> ".cabal" 
```
So I have a function that can get cabal file. I'm gonna refactor into smaller functions. Like the the part under the `where` clause should be its own function `Issue -> Request`. But anyways, I wanted to ask about how we should handle errors. We can get the status code of the request as an `Int` and based of off that throw an error/log. There are many cases of status code though. If the the request is succesful we get `200`, so I think it the case statement would look something like this:
```
case statusCode of
    200 -> return responsebody
    otherCode -> logCodeAndthrowError otherCode
```
Or something like this. I'm gonna work on getting the category from the file now.

**Comment by rashadg1030** [comment]
```
fetchRepoCategories :: MonadIO m => Repo -> m (SqlArray Category)
fetchRepoCategories repo = do
    cabalFile <- repoCabalFile repo 
    pure $ case parseGenericPackageDescriptionMaybe cabalFile of
        Nothing -> SqlArray []
        Just genPkgDescr -> 
            SqlArray 
            $ Category
            <$> strip 
            <$> (splitOn "," $ pack $ category $ packageDescription genPkgDescr)
```
Wanted to use (\case ....) in this `do` block but couldn't because of `Maybe`. Is there a better way to style this?

**Comment by rashadg1030** [comment]
@chshersh I think this branch can be closed.

**Comment by rashadg1030** [comment]
Added testing. Gonna add documentation and fix function so it passes a test.

**Comment by rashadg1030** [comment]
@chshersh This branch is redundant. Branch #119 solves this PR.

**Comment by chshersh** [comment]
@rashadg1030 Got it :+1: Closing this PR then.

**Pull request closed without merging**
